### PR TITLE
provide a static library for x86_energy without external dependencies...

### PR DESCRIPTION
**Pull request by SvenSchiffner**
… to x86_adapt and correct CMake to update submodules the right way

### CODE REVIEW

**Comment by AndreasGocht** [comment]
Ok. This time I ended up with:
```
Scanning dependencies of target x86_energy
[ 10%] Creating directories for 'x86_energy'
[ 20%] No download step for 'x86_energy'
[ 30%] No patch step for 'x86_energy'
[ 40%] No update step for 'x86_energy'
[ 50%] Performing configure step for 'x86_energy'
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: /sw/global/compilers/gcc/5.3.0/bin/gcc
-- Check for working C compiler: /sw/global/compilers/gcc/5.3.0/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /sw/global/compilers/gcc/5.3.0/bin/g++
-- Check for working CXX compiler: /sw/global/compilers/gcc/5.3.0/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:45 (include):
  include could not find load file:

    common/FindMSR.cmake


Found neither libx86_adapt nor libmsr! Building libmsr.
-- Configuring incomplete, errors occurred!
See also "/home/gocht/support/scorep_plugin_x86_energy/build/x86_energy-prefix/src/x86_energy-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [x86_energy-prefix/src/x86_energy-stamp/x86_energy-configure] Fehler 1
make[1]: *** [CMakeFiles/x86_energy.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by AndreasGocht** [comment]
Ok with
```cmake ../ -DCMAKE_INSTALL_PREFIX=~/lib -DX86_ENERGY_LIBRARIES=/usr/local/lib/libx86_adapt.so -DX86_ENERGY_INCLUDE_DIRS=/usr/local/include/```


it worked. but then I end up with:

```
gocht@taurusi6605:~/support/scorep_plugin_x86_energy/build$ make
Scanning dependencies of target x86_energy_plugin
[ 50%] Building CXX object CMakeFiles/x86_energy_plugin.dir/x86_energy_plugin.cpp.o
/home/gocht/support/scorep_plugin_x86_energy/x86_energy_plugin.cpp:49:24: schwerwiegender Fehler: x86_energy.h: Datei oder Verzeichnis nicht gefunden
Kompilierung beendet.
make[2]: *** [CMakeFiles/x86_energy_plugin.dir/x86_energy_plugin.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/x86_energy_plugin.dir/all] Fehler 2
make: *** [all] Fehler 2
```

**Comment by AndreasGocht** [comment]
OK ... I messed up the git projects ...

**Comment by rschoene** [comment]
Hallo, geht noch nicht:

rschoene@carbila:~/projekte/readex/test/scorep_plugin_x86_energy/build$ cmake ../
-- The C compiler identification is GNU 5.4.0

...

Klone nach 'scorep_cxx_wrapper' ...
Submodul-Pfad: 'scorep_cxx_wrapper': '547bc958d559e7c3ab3392010df6648c44e7d41e' ausgecheckt
**Klone nach 'x86_energy' ...
fatal: Referenz ist kein "Tree"-Objekt: cd0063f8564aedc508d71a8e44ad0074f32b6735
Konnte 'cd0063f8564aedc508d71a8e44ad0074f32b6735' in Submodul-Pfad 'x86_energy' nicht auschecken.**
-- Setting build type to 'Debug' as none was specified.
-- Building x86_energy

...

**Comment by SvenSchiffner** [comment]
This is a little mess with the submodules because the referenced commit is a part of my pull request. So if you accept the pull request I can update the submodule to the latest version of x86_energy and everything should work.

**Pull request merged**
